on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

name: catalog

jobs:
  catalog:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
    container: eco4cast/rocker-neon4cast:latest
    steps:
      - run: git config --system --add safe.directory '*'

      - uses: actions/checkout@v3
        with:
          ref: prod
          fetch-depth: 0
          set-safe-directory: '*'

      - name: install validator
        run: |
          pip install stac-validator

      - name: Render
        shell: Rscript {0}
        run: source("catalog/update_stac.R")

      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add catalog/* .
          git commit -a -m "update catalog" || echo "nothing to commit"
          git push https://${GITHUB_PAT}:${GITHUB_PAT}@github.com/${GITHUB_REPOSITORY}
