# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

name: gefs_osn

jobs:
  docker:
    runs-on: [self-hosted]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
#    container: rocker/geospatial
    steps:
      - uses: actions/checkout@v3
        with:
          ref: prod

      - name: Install
        shell: Rscript {0}
        run: |
          #devtools::install(dependencies=TRUE, upgrade="never")
          install.packages("remotes")
          remotes::install_github("eco4cast/gefs4cast")

      - name: Update GEFS
        shell: Rscript {0}
        run: |
          source("drivers/download_stage1_psuedo.R")

      - name: Generate stage 2
        shell: Rscript {0}
        run: |
          source("drivers/generate_stage2.R")


      - name: Update Stage3
        shell: Rscript {0}
        run: |
          source("drivers/update_stage3.R")

