# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  #schedule:
  #  - cron: '0 0 * * *'
  workflow_dispatch:

name: scoring

jobs:
  docker:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    timeout-minutes: 1440
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
    #container: eco4cast/rocker-neon4cast:latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: score4casts # TODO: change this to prod when happy

      - name: Install
        shell: Rscript {0}
        run: |
          remotes::install_deps(".", dep=TRUE)

      - name: Generate scores
        shell: Rscript {0}
        run: |
          source("scoring/scoring.R")

      - name: Update inventory
        shell: Rscript {0}
        run: |
          source("scoring/build_score_inventory.R")
